name: meme_gpt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0  # Correctly placed now

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/memes/
